In [1]:
!pip install tensorflow-datasets

  Created wheel for promise: filename=promise-2.3-py3-none-any.whl size=21494 sha256=d19734272f3828bc2c1f3b3a9efaa41fa356956d755aa6d153a4db6607a922b5
  Stored in directory: c:\users\amanpreet singh\appdata\local\pip\cache\wheels\29\93\c6\762e359f8cb6a5b69c72235d798804cae523bbe41c2aa8333d
Successfully built promise
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.11.2
    Uninstalling protobuf-3.11.2:
      Successfully uninstalled protobuf-3.11.2
  Attempting uninstall: googleapis-common-protos
    Found existing installation: googleapis-common-protos 1.51.0
    Uninstalling googleapis-common-protos-1.51.0:
      Successfully uninstalled googleapis-common-protos-1.51.0


In [2]:
import tensorflow as tf
import tensorflow_datasets as tfds

In [3]:
mnist_data = tfds.load("fashion_mnist")

Dataset fashion_mnist downloaded and prepared to C:\Users\Amanpreet Singh\tensorflow_datasets\fashion_mnist\3.0.1. Subsequent calls will reuse this data.


In [5]:
type(mnist_data)

dict

In [6]:
for item in mnist_data:
    print(item)
    print(type(item))

train
<class 'tensorflow_datasets.core.splits.Split'>
test
<class 'tensorflow_datasets.core.splits.Split'>


In [9]:
mnist_train = tfds.load(name="fashion_mnist", split="train")
assert isinstance(mnist_train, tf.data.Dataset)
print(type(mnist_train))

<class 'tensorflow.python.data.ops.dataset_ops.PrefetchDataset'>


In [10]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())

<class 'dict'>
dict_keys(['image', 'label'])


In [11]:
for item in mnist_train.take(1):
    print(type(item))
    print(item.keys())
    print(item['image'])
    print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


In [12]:
mnist_test, info = tfds.load(name="fashion_mnist", with_info="true")
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    full_name='fashion_mnist/3.0.1',
    description="""
    Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.
    """,
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    data_path='C:\\Users\\Amanpreet Singh\\tensorflow_datasets\\fashion_mnist\\3.0.1',
    download_size=29.45 MiB,
    dataset_size=36.42 MiB,
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    supervised_keys=('image', 'label'),
    disable_shuffling=False,
    splits={
        'test': <SplitInfo num_examples=10000, num_shards=1>,
        'train': <SplitInfo num_examples=60000, num_shards=1>,
    },
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
      author

In [13]:
data = tfds.load('cats_vs_dogs', split='train', as_supervised=True)

Dataset cats_vs_dogs downloaded and prepared to C:\Users\Amanpreet Singh\tensorflow_datasets\cats_vs_dogs\4.0.0. Subsequent calls will reuse this data.


In [14]:
data = tfds.load('cats_vs_dogs', split='train[:10000]', as_supervised=True)

In [15]:
data = tfds.load('cats_vs_dogs', split='train[:20%]', as_supervised=True)

In [16]:
data = tfds.load('cats_vs_dogs', split='train[-1000:]+train[:1000]', as_supervised=True)

In [17]:
train_data = tfds.load('cats_vs_dogs', split='train[:80%]', as_supervised=True)
validation_data = tfds.load('cats_vs_dogs', split='train[80%:90%]', as_supervised=True)
test_data = tfds.load('cats_vs_dogs', split='train[-10%:]', as_supervised=True)

In [18]:
train_length = [i for i,_ in enumerate(train_data)][-1] + 1
print(train_length)

18610


In [21]:
filename="C:\\Users\\Amanpreet Singh\\tensorflow_datasets\\cats_vs_dogs\\4.0.0\\cats_vs_dogs-train.tfrecord-00000-of-00008"
raw_dataset = tf.data.TFRecordDataset(filename)
for raw_record in raw_dataset.take(1):
    print(repr(raw_record))

<tf.Tensor: shape=(), dtype=string, numpy=b'\n\xc9\xd8\x01\n\x0e\n\x05label\x12\x05\x1a\x03\n\x01\x01\n-\n\x0eimage/filename\x12\x1b\n\x19\n\x17PetImages\\Dog\\10396.jpg\n\x86\xd8\x01\n\x05image\x12\xfb\xd7\x01\n\xf7\xd7\x01\n\xf3\xd7\x01\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xfe\x00>CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), default quality\n\xff\xdb\x00C\x00\x08\x06\x06\x07\x06\x05\x08\x07\x07\x07\t\t\x08\n\x0c\x14\r\x0c\x0b\x0b\x0c\x19\x12\x13\x0f\x14\x1d\x1a\x1f\x1e\x1d\x1a\x1c\x1c $.\' ",#\x1c\x1c(7),01444\x1f\'9=82<.342\xff\xdb\x00C\x01\t\t\t\x0c\x0b\x0c\x18\r\r\x182!\x1c!22222222222222222222222222222222222222222222222222\xff\xc0\x00\x11\x08\x01\x06\x01^\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1f\x00\x00\x01\x05\x01\x01\x01\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\x0b\xff\xc4\x00\xb5\x10\x00\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\x00\x00\x01}\x01\x02\x03\x00\x04\x11\x05\x12!1A\x06\x13Qa\x07"q

In [31]:
!pip install tensorflow-addons

### ETL

In [27]:
import tensorflow as tf
import tensorflow_datasets as tfds
#import tensorflow_addons as tfa

In [28]:
# MODEL DEFINITION START #
model = tf.keras.models.Sequential([
                tf.keras.layers.Conv2D(16, (3,3), activation='relu', input_shape=(300, 300, 3)),
                tf.keras.layers.MaxPooling2D(2, 2),
                tf.keras.layers.Conv2D(32, (3,3), activation='relu'),
                tf.keras.layers.MaxPooling2D(2,2),
                tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
                tf.keras.layers.MaxPooling2D(2,2),
                tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
                tf.keras.layers.MaxPooling2D(2,2),
                tf.keras.layers.Conv2D(64, (3,3), activation='relu'),
                tf.keras.layers.MaxPooling2D(2,2),
                tf.keras.layers.Flatten(),
                tf.keras.layers.Dense(512, activation='relu'),
                tf.keras.layers.Dense(1, activation='sigmoid')
    ])
model.compile(optimizer='Adam', loss='binary_crossentropy',
metrics=['accuracy'])
# MODEL DEFINITION END #

In [29]:
# EXTRACT PHASE START #
data = tfds.load('horses_or_humans', split='train', as_supervised=True)
val_data = tfds.load('horses_or_humans', split='test', as_supervised=True)
# EXTRACT PHASE END

Dataset horses_or_humans downloaded and prepared to C:\Users\Amanpreet Singh\tensorflow_datasets\horses_or_humans\3.0.0. Subsequent calls will reuse this data.


In [32]:
# TRANSFORM PHASE START #
def augmentimages(image, label):
    image = tf.cast(image, tf.float32)
    image = (image/255)
    image = tf.image.random_flip_left_right(image)
    image = tfa.image.rotate(image, 40, interpolation='NEAREST')
    return image, label
#train = data.map(augmentimages)
#train_batches = train.shuffle(100).batch(32)
train_batches = data.shuffle(100).batch(32)
validation_batches = val_data.batch(32)
# TRANSFORM PHASE END

In [ ]:
# LOAD PHASE START #
history = model.fit(train_batches, epochs=10, validation_data=validation_batches, validation_steps=1)
# LOAD PHASE END #

### parallelizing

In [33]:
train_data = tfds.load('cats_vs_dogs', split='train', with_info=True)

In [36]:
#file_pattern = f'C:\\Users\\Amanpreet Singh\\tensorflow_datasets\\cats_vs_dogs\\4.0.0\\cats_vs_dogs-train*'
file_pattern = f'C:\\Users\\Amanpreet Singh\\tensorflow_datasets\\cats_vs_dogs\\4.0.0\\cats_vs_dogs-train*'
files = tf.data.Dataset.list_files(file_pattern)

In [37]:
train_dataset = files.interleave(
                        tf.data.TFRecordDataset,
                        cycle_length=4,
                        num_parallel_calls=tf.data.experimental.AUTOTUNE
                        )

In [38]:
def read_tfrecord(serialized_example):
    feature_description={
                            "image": tf.io.FixedLenFeature((), tf.string, ""),
                            "label": tf.io.FixedLenFeature((), tf.int64, -1),
                            }
    example = tf.io.parse_single_example(
                            serialized_example, feature_description
                            )
    image = tf.io.decode_jpeg(example['image'], channels=3)
    image = tf.cast(image, tf.float32)
    image = image / 255
    image = tf.image.resize(image, (300,300))
    return image, example['label']

In [40]:
import multiprocessing
cores = multiprocessing.cpu_count()
print(cores)
train_dataset = train_dataset.map(read_tfrecord, num_parallel_calls=cores)
train_dataset = train_dataset.cache()

4


In [41]:
train_dataset = train_dataset.shuffle(1024).batch(32)
train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)